/**
 * Build smoke test — verifies the esbuild pipeline produced valid artifacts.
 * Runs against the dist/ outputs (regenerated by `npm run build` via pretest).
 */

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { getModule } = require('../helpers');

const DIST = path.join(__dirname, '..', '..', 'dist');

describe('Build (esbuild)', function() {
  const required = [
    'card-framework.js',
    'card-framework.min.js',
    'card-framework.esm.js',
    'card-framework.cjs.js',
    'card-framework.css',
  ];

  required.forEach(function(file) {
    it('should emit ' + file, function() {
      assert.strictEqual(fs.existsSync(path.join(DIST, file)), true, file + ' missing');
    });
  });

  it('should expose CardFrame via CJS bundle', function() {
    const CF = getModule();
    assert.strictEqual(typeof CF.CardFrame, 'function');
    assert.strictEqual(Object.keys(CF).length >= 25, true);
  });

  it('IIFE bundle should set window.CardFrame', function() {
    const code = fs.readFileSync(path.join(DIST, 'card-framework.js'), 'utf8');
    assert.strictEqual(code.indexOf('window.CardFrame') !== -1, true);
  });

  it('minified bundle should be smaller than full IIFE', function() {
    const full = fs.statSync(path.join(DIST, 'card-framework.js')).size;
    const min = fs.statSync(path.join(DIST, 'card-framework.min.js')).size;
    assert.strictEqual(min < full, true);
  });
});
